Repository metwork-framework/docker-mfxxx-centos6-buildimage, pull requests merged in 2018-10, with the labels that each got.

#5 chore: typo
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#6 chore: use conditional downstream
  .drone.yml
Labels: Status: Review Needed, Type: Enhancement

#7 chore: fix latest change
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#4 chore: limit branch building
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#8 chore: don't push identical image
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#9 chore: update buildimage hash (in case mfcom has changed)
  Dockerfile
Labels: Status: Review Needed, Type: To Categorize

#10 build: better cache invalidation
  Dockerfile
Labels: Status: Review Needed

#13 build: move specific part of README
  .metwork-framework/README.md
Labels: Status: Review Needed
